[[rulesets]]
group = "ğŸ¯ ç›´è¿"
ruleset = "rules/Direct/LAN.list"

[[rulesets]]
group = "ğŸ¯ ç›´è¿"
ruleset = "rules/Direct/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ ç›´è¿"
ruleset = "rules/Direct/ChinaIP.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆª"
ruleset = "rules/Reject/BanAD.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆª"
ruleset = "rules/Reject/BanEasy.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆª"
ruleset = "rules/Reject/BanEasyChina.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆª"
ruleset = "rules/Reject/BanEasyPrivacy.list"

[[rulesets]]
group = "ğŸ›‘ æ‹¦æˆª"
ruleset = "rules/Reject/BanProgramAD.list"

[[rulesets]]
group = "Netflix"
ruleset = "rules/Proxy/Netflix.list"

[[rulesets]]
group = "Bilibili"
ruleset = "rules/Proxy/Bilibili.list"

[[rulesets]]
group = "OpenAI"
ruleset = "rules/Proxy/OpenAI.list"

[[rulesets]]
group = "Google"
ruleset = "rules/Proxy/Google.list"

[[rulesets]]
group = "Microsoft"
ruleset = "rules/Proxy/Microsoft.list"

[[rulesets]]
group = "Apple"
ruleset = "rules/Proxy/Apple.list"

[[rulesets]]
group = "GFW"
ruleset = "rules/Proxy/GFW.list"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
